services:
  postgres:
    image: postgres:12
    container_name: postgres
    hostname: database
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: crm
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5430:5432"

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapi
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/crm
      SPRING_DATASOURCE_USERNAME: crm
      SPRING_DATASOURCE_PASSWORD: crm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
